module.exports = {
	USER_CONNECTED:"USER_CONNECTED",
	USER_DISCONNECTED:"USER_DISCONNECTED",
	VERIFY_USER:"VERIFY_USER",
	LOGOUT:"LOGOUT",
	SERVER_UPDATE:"SERVER_UPDATE",
	PLAYER_INPUT:"PLAYER_INPUT",
	CREATE_GAME:"CREATE_GAME",
	JOIN_GAME:"JOIN_GAME",
	LEAVE_GAME:"LEAVE_GAME",
	GAME_OVER:"GAME_OVER",
	ACTIVE_GAME:"ACTIVE_GAME",
	CLIENT_ADDED:"CLIENT_ADDED",
	UPDATE_LIST:"UPDATE_LIST",
	WINNER:"WINNER",
	LOSER:"LOSER",
	LEAVE:"LEAVE"
}
